import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import { MenuContext, MenuProvider } from "./components/context/MenuContext";
import NavBarMain from "./components/navbar/NavBarMain";
import Header from "./components/header/Header";

const inter = Inter({ subsets: ["latin"] });
// const logoPath = "/assets/logoClinMais.jpg";

export const metadata: Metadata = {
  title: "CLIN+",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body className={`inter.className bg-backg`}>
        <MenuProvider>
          <div className=" max-w-7xl  mx-auto">
            <Header />
            <NavBarMain />
            {children}
            <main className="flex flex-col items-center p-2"></main>
          </div>
        </MenuProvider>

        {/* header */}
      </body>
    </html>
  );
}
