import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Navbar } from "./components";
import Image from "next/image";
import Link from "next/link";

import NavBarMain2 from "./components/navbar/NavBarMain2";
import NavBar3 from "./components/navbar/NavBarMobile";
import IconBarOficial from "./components/icons/IconBarOficial";
import IconUser from "./components/icons/IconUser";
import BtnMobileMenu from "./components/navbar/BtnMobileMenu";
import NavBarMobile from "./components/navbar/NavBarMobile";
import BtnMenuUser from "./components/navbar/BtnMenuUser";
import { MenuContext, MenuProvider } from "./components/navbar/MenuContext";

const inter = Inter({ subsets: ["latin"] });
const logoPath = "/assets/logoClinMais.jpg";

export const metadata: Metadata = {
  title: "CLIN+",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body className={`inter.className bg-backg`}>
        <MenuProvider>
          <div className="bg-green2 h-16 px-4 sm:px-6 lg:px-8 max-w-7xl mx-auto">
            <div className="flex md:justify-between items-center text-white h-full ">
              {/* NavBarMobile - usado como menu principal */}
              <NavBarMobile className="hidden md:flex hover:text-orange2 hover:font-bold" />
              <div className="md:hidden px-4 ">
                <BtnMobileMenu />
              </div>
              <BtnMenuUser />
              <button
                type="button"
                id="menuButton"
                className="hover:text-orange2 font-bold hover:stroke-white focus:outline-none duration-200 ease-in-out"
                aria-label="Menu"
                aria-expanded="false"
              ></button>
            </div>
          </div>
          {children}

          <main className="flex flex-col items-center p-2"></main>
        </MenuProvider>

        {/* header */}
        <header>
          {/* <Image
                src={logoPath}
                alt="logo clim mais"
                width={80} // Defina a largura desejada
                height={80} // Defina a altura desejada
                className="w-12 h-auto rounded-full p-2" // Defina as classes CSS desejadas
              /> */}
          {/* </div> */}
        </header>
      </body>
    </html>
  );
}
